name: Deploy

on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -t yaoa/bitprint:build -f ./Dockerfile .
      - name: Login
        env:
          dockerID: ${{ secrets.dockerID }}
          dockerPassword: ${{ secrets.dockerPassword }}
        run: |
          docker login -u $dockerID -p $dockerPassword
      - name: Deploy Commit ID
        if: ${{ github.head_ref == '' && github.sha != '' }}
        run: |
          docker tag yaoa/bitprint:build yaoa/bitprint:$GITHUB_SHA
          docker push yaoa/bitprint:$GITHUB_SHA
      - name: Deploy Latest
        if: ${{ github.head_ref == '' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: |
          docker tag yaoa/bitprint:build yaoa/bitprint:latest
          docker push yaoa/bitprint:latest
      - name: Deploy Develop
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/dev') }}
        run: |
          docker tag yaoa/bitprint:build yaoa/bitprint:latest-develop
          docker push yaoa/bitprint:latest-develop
      - name: Deploy Branch
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/') && github.event_name == 'push' }}
        run: |
          docker tag yaoa/bitprint:build yaoa/bitprint:${GITHUB_REF##*/}
          docker push yaoa/bitprint:${GITHUB_REF##*/}
      - name: Deploy Tag
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker tag yaoa/bitprint:build yaoa/bitprint:${GITHUB_REF##*/}
          docker push yaoa/bitprint:${GITHUB_REF##*/}
